export const governorates = [
  { id: "Alexandria", name: "الإسكندرية" },
  { id: "Aswan", name: "أسوان" },
  { id: "Asyut", name: "أسيوط" },
  { id: "Beheira", name: "البحيرة" },
  { id: "Beni Suef", name: "بني سويف" },
  { id: "Cairo", name: "القاهرة" },
  { id: "Dakahlia", name: "الدقهلية" },
  { id: "Damietta", name: "دمياط" },
  { id: "Faiyum", name: "الفيوم" },
  { id: "Gharbia", name: "الغربية" },
  { id: "Giza", name: "الجيزة" },
  { id: "Ismailia", name: "الإسماعيلية" },
  { id: "Kafr El Sheikh", name: "كفر الشيخ" },
  { id: "Luxor", name: "الأقصر" },
  { id: "Matrouh", name: "مطروح" },
  { id: "Minya", name: "المنيا" },
  { id: "Monufia", name: "المنوفية" },
  { id: "New Valley", name: "الوادي الجديد" },
  { id: "Suez", name: "السويس" },
  { id: "Oases", name: "الواحات" },
  { id: "North Sinai", name: "شمال سيناء" },
  { id: "Port Said", name: "بورسعيد" },
  { id: "Qalyubia", name: "القليوبية" },
  { id: "Qena", name: "قنا" },
  { id: "Red Sea", name: "البحر الأحمر" },
  { id: "Sharqia", name: "الشرقية" },
  { id: "Sohag", name: "سوهاج" },
  { id: "South Sinai", name: "جنوب سيناء" },
];
